In [20]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression 
from sklearn.preprocessing import LabelEncoder 
from sklearn.metrics import r2_score
import pickle

In [9]:
cars_data = pd.read_csv("Cardetails.csv")
cars_data.head(8)

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner,mileage,engine,max_power,torque,seats
0,Maruti Swift Dzire VDI,2014,450000,145500,Diesel,Individual,Manual,First Owner,23.4 kmpl,1248 CC,74 bhp,190Nm@ 2000rpm,5.0
1,Skoda Rapid 1.5 TDI Ambition,2014,370000,120000,Diesel,Individual,Manual,Second Owner,21.14 kmpl,1498 CC,103.52 bhp,250Nm@ 1500-2500rpm,5.0
2,Honda City 2017-2020 EXi,2006,158000,140000,Petrol,Individual,Manual,Third Owner,17.7 kmpl,1497 CC,78 bhp,"12.7@ 2,700(kgm@ rpm)",5.0
3,Hyundai i20 Sportz Diesel,2010,225000,127000,Diesel,Individual,Manual,First Owner,23.0 kmpl,1396 CC,90 bhp,22.4 kgm at 1750-2750rpm,5.0
4,Maruti Swift VXI BSIII,2007,130000,120000,Petrol,Individual,Manual,First Owner,16.1 kmpl,1298 CC,88.2 bhp,"11.5@ 4,500(kgm@ rpm)",5.0
5,Hyundai Xcent 1.2 VTVT E Plus,2017,440000,45000,Petrol,Individual,Manual,First Owner,20.14 kmpl,1197 CC,81.86 bhp,113.75nm@ 4000rpm,5.0
6,Maruti Wagon R LXI DUO BSIII,2007,96000,175000,LPG,Individual,Manual,First Owner,17.3 km/kg,1061 CC,57.5 bhp,"7.8@ 4,500(kgm@ rpm)",5.0
7,Maruti 800 DX BSII,2001,45000,5000,Petrol,Individual,Manual,Second Owner,16.1 kmpl,796 CC,37 bhp,59Nm@ 2500rpm,4.0

In [4]:
cars_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8128 entries, 0 to 8127
Data columns (total 13 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   name           8128 non-null   object
 1   year           8128 non-null   int64
 2   selling_price  8128 non-null   int64
 3   km_driven      8128 non-null   int64
 4   fuel           8128 non-null   object
 5   seller_type    8128 non-null   object
 6   transmission   8128 non-null   object
 7   owner          8128 non-null   object
 8   mileage        7907 non-null   object
 9   engine         7907 non-null   object
 10  max_power      7913 non-null   object
 11  torque         7906 non-null   object
 12  seats          7907 non-null   float64
dtypes: float64(1), int64(3), object(9)
memory usage: 825.6+ KB

In [7]:
cars_data["seller_type"].unique()

array(['Individual', 'Dealer', 'Trustmark Dealer'], dtype=object)

In [10]:
cars_data.drop(columns = ['torque'], inplace = True)

In [142]:
cars_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8128 entries, 0 to 8127
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   name           8128 non-null   object
 1   year           8128 non-null   int64
 2   selling_price  8128 non-null   int64
 3   km_driven      8128 non-null   int64
 4   fuel           8128 non-null   object
 5   seller_type    8128 non-null   object
 6   transmission   8128 non-null   object
 7   owner          8128 non-null   object
 8   mileage        7907 non-null   object
 9   engine         7907 non-null   object
 10  max_power      7913 non-null   object
 11  seats          7907 non-null   float64
dtypes: float64(1), int64(3), object(8)
memory usage: 762.1+ KB

In [11]:
cars_data.dropna(inplace=True)

In [144]:
cars_data.isnull().sum()

name             0
year             0
selling_price    0
km_driven        0
fuel             0
seller_type      0
transmission     0
owner            0
mileage          0
engine           0
max_power        0
seats            0
dtype: int64

In [145]:
cars_data.duplicated().sum()

np.int64(1189)

In [146]:
cars_data.shape

(7907, 12)

In [51]:
# for col in cars_data.columns:
#     print("Unique value of" + col)
#     print(cars_data[col].unique())

In [12]:
def splitCarName(carName):
    carName = carName.split(' ')[0]
    return carName

cars_data['name'] = cars_data['name'].apply(splitCarName)

In [13]:
def splitMileage(mileage):
    value = mileage.split(' ')[0]
    return float(value)
    
cars_data["mileage"] = cars_data["mileage"].apply(splitMileage)

In [14]:
def splitEngine(engine):
    value = engine.split(' ')[0]
    return float(value)
    
cars_data["engine"] = cars_data["engine"].apply(splitEngine)

In [15]:
def splitMax_power(max_power):
    value = max_power.split(' ')[0]
    return value

cars_data["max_power"] = cars_data["max_power"].apply(splitMax_power)

In [16]:
cars_data["max_power"].unique()
cars_data["max_power"]=pd.to_numeric(cars_data["max_power"],errors="coerce")
cars_data.dropna(inplace=True)

In [163]:
cars_data.head()

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner,mileage,engine,max_power,seats
0,20.0,2014,450000,145500,1.0,1.0,1.0,0.0,23.40,1248.0,74,5.0
1,26.0,2014,370000,120000,1.0,1.0,1.0,2.0,21.14,1498.0,103.52,5.0
2,10.0,2006,158000,140000,3.0,1.0,1.0,4.0,17.70,1497.0,78,5.0
3,11.0,2010,225000,127000,1.0,1.0,1.0,0.0,23.00,1396.0,90,5.0
4,20.0,2007,130000,120000,3.0,1.0,1.0,0.0,16.10,1298.0,88.2,5.0

In [17]:
cars_data.dtypes

name              object
year               int64
selling_price      int64
km_driven          int64
fuel              object
seller_type       object
transmission      object
owner             object
mileage          float64
engine           float64
max_power        float64
seats            float64
dtype: object

In [18]:
le=LabelEncoder()
cars_data['name']=le.fit_transform(cars_data["name"]).astype(float)
cars_data['fuel']=le.fit_transform(cars_data["fuel"]).astype(float)
cars_data['seller_type']=le.fit_transform(cars_data["seller_type"]).astype(float)
cars_data['transmission']=le.fit_transform(cars_data["transmission"]).astype(float)
cars_data['owner']=le.fit_transform(cars_data["owner"]).astype(float)
display(cars_data.head(10))

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner,mileage,engine,max_power,seats
0,20.0,2014,450000,145500,1.0,1.0,1.0,0.0,23.40,1248.0,74.00,5.0
1,26.0,2014,370000,120000,1.0,1.0,1.0,2.0,21.14,1498.0,103.52,5.0
2,10.0,2006,158000,140000,3.0,1.0,1.0,4.0,17.70,1497.0,78.00,5.0
3,11.0,2010,225000,127000,1.0,1.0,1.0,0.0,23.00,1396.0,90.00,5.0
4,20.0,2007,130000,120000,3.0,1.0,1.0,0.0,16.10,1298.0,88.20,5.0
5,11.0,2017,440000,45000,3.0,1.0,1.0,0.0,20.14,1197.0,81.86,5.0
6,20.0,2007,96000,175000,2.0,1.0,1.0,0.0,17.30,1061.0,57.50,5.0
7,20.0,2001,45000,5000,3.0,1.0,1.0,2.0,16.10,796.0,37.00,4.0
8,28.0,2011,350000,90000,1.0,1.0,1.0,0.0,23.59,1364.0,67.10,5.0
9,9.0,2013,200000,169000,1.0,1.0,1.0,0.0,20.00,1399.0,68.10,5.0

In [21]:

# X = df[["name", "year", "km_driven", "fuel", "seller_type","transmission", "owner", "mileage", "engine", "max_power","seats"]]
X = cars_data.drop(columns = 'selling_price')
y = cars_data["selling_price"]

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size = 0.2,
    random_state = 42
)

model = LinearRegression()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

# accuracy = model.score(X, y)
print("Actual Values:")
print(y_test.values)

print("\nPredict Values:")
print(y_pred)

print(r2_score(y_test, y_pred))
with open ("model.pkl", "wb") as f:
    pickle.dump(model, f)

Actual Values:
[ 501000  440000  140000 ...  144000 2711000  680000]

Predict Values:
[ 618484.36374223  424382.56553888   75549.46320015 ...  211996.4989568
 2533110.27165847  639123.14651284]
0.6946494274737635